#Can one block of except statements handle multiple exception? 


'''
    answer: 
            In Python, try-except blocks can be used to catch and respond to one or multiple exceptions. 
            In cases where a process raises more than one possible exception, 
            they can all be handled using a single except clause.
'''
